SPACESHIP_CHAR_SYMBOL=❯
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_VI_MODE_SHOW=false
SPACESHIP_VENV_PREFIX="via 🐍 "
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_PREFIX="\e[31mexit code:\e[39m "
SPACESHIP_EXIT_CODE_SYMBOL=""
SPACESHIP_HOST_PREFIX="at 🏠 "
